"""
Real engine fingerprint pools from browser captures (macOS, minimal top-level document).

Used to mirror Sentinel sdk.js behavior:
  - R(pool): uniform random element (empty pool -> None)
  - T(): random navigator prototype key + U+2212 + value string (dynamic keys below)

Pools are engine-specific: do not mix Chromium keys into Gecko or WebKit profiles.
"""

from __future__ import annotations

from typing import Dict, Final, Optional, Tuple

# --- Chromium (Chrome) — captured at v146 ---
# Object.keys(document) on about:blank-style top-level document.
CHROME_DOCUMENT_OWN_KEYS: Final[Tuple[str, ...]] = ("location",)

# Number("name" in window) for sdk.js slots 18–24 (order: ai, createPRNG, cache, data, solana, dump, InstallTrigger).
CHROME_IN_WINDOW_BITS: Final[Tuple[int, ...]] = (0, 0, 0, 0, 0, 0, 0)

# Object.keys(Object.getPrototypeOf(navigator)) — order preserved from capture.
CHROME_NAVIGATOR_PROTOTYPE_KEYS: Final[Tuple[str, ...]] = (
    "vendorSub",
    "productSub",
    "vendor",
    "maxTouchPoints",
    "scheduling",
    "userActivation",
    "geolocation",
    "doNotTrack",
    "webkitTemporaryStorage",
    "webkitPersistentStorage",
    "hardwareConcurrency",
    "cookieEnabled",
    "appCodeName",
    "appName",
    "appVersion",
    "platform",
    "product",
    "userAgent",
    "language",
    "languages",
    "onLine",
    "webdriver",
    "plugins",
    "mimeTypes",
    "pdfViewerEnabled",
    "connection",
    "getGamepads",
    "javaEnabled",
    "sendBeacon",
    "vibrate",
    "windowControlsOverlay",
    "deprecatedRunAdAuctionEnforcesKAnonymity",
    "protectedAudience",
    "bluetooth",
    "clipboard",
    "credentials",
    "keyboard",
    "managed",
    "mediaDevices",
    "serviceWorker",
    "virtualKeyboard",
    "wakeLock",
    "deviceMemory",
    "userAgentData",
    "locks",
    "storage",
    "gpu",
    "login",
    "ink",
    "mediaCapabilities",
    "devicePosture",
    "hid",
    "mediaSession",
    "permissions",
    "presentation",
    "serial",
    "usb",
    "xr",
    "storageBuckets",
    "adAuctionComponents",
    "runAdAuction",
    "canLoadAdAuctionFencedFrame",
    "canShare",
    "share",
    "clearAppBadge",
    "getBattery",
    "getUserMedia",
    "requestMIDIAccess",
    "requestMediaKeySystemAccess",
    "setAppBadge",
    "webkitGetUserMedia",
    "clearOriginJoinedAdInterestGroups",
    "createAuctionNonce",
    "joinAdInterestGroup",
    "leaveAdInterestGroup",
    "updateAdInterestGroups",
    "deprecatedReplaceInURN",
    "deprecatedURNToURL",
    "getInstalledRelatedApps",
    "getInterestGroupAdAuctionData",
    "registerProtocolHandler",
    "unregisterProtocolHandler",
)

# Static navigator[k] stringifications for T() when k is not userAgent/language/languages (filled from capture).
CHROME_NAVIGATOR_STATIC_STRINGS: Final[Dict[str, str]] = {
    "vendorSub": "",
    "productSub": "20030107",
    "vendor": "Google Inc.",
    "maxTouchPoints": "0",
    "scheduling": "[object Scheduling]",
    "userActivation": "[object UserActivation]",
    "geolocation": "[object Geolocation]",
    "doNotTrack": "null",
    "webkitTemporaryStorage": "[object DeprecatedStorageQuota]",
    "webkitPersistentStorage": "[object DeprecatedStorageQuota]",
    "hardwareConcurrency": "12",
    "cookieEnabled": "true",
    "appCodeName": "Mozilla",
    "appName": "Netscape",
    "appVersion": "5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36",
    "platform": "MacIntel",
    "product": "Gecko",
    "onLine": "true",
    "webdriver": "false",
    "plugins": "[object PluginArray]",
    "mimeTypes": "[object MimeTypeArray]",
    "pdfViewerEnabled": "true",
    "connection": "[object NetworkInformation]",
    "getGamepads": "function getGamepads() { [native code] }",
    "javaEnabled": "function javaEnabled() { [native code] }",
    "sendBeacon": "function sendBeacon() { [native code] }",
    "vibrate": "function vibrate() { [native code] }",
    "windowControlsOverlay": "[object WindowControlsOverlay]",
    "deprecatedRunAdAuctionEnforcesKAnonymity": "false",
    "protectedAudience": "[object ProtectedAudience]",
    "bluetooth": "[object Bluetooth]",
    "clipboard": "[object Clipboard]",
    "credentials": "[object CredentialsContainer]",
    "keyboard": "[object Keyboard]",
    "managed": "[object NavigatorManagedData]",
    "mediaDevices": "[object MediaDevices]",
    "serviceWorker": "[object ServiceWorkerContainer]",
    "virtualKeyboard": "[object VirtualKeyboard]",
    "wakeLock": "[object WakeLock]",
    "deviceMemory": "8",
    "userAgentData": "[object NavigatorUAData]",
    "locks": "[object LockManager]",
    "storage": "[object StorageManager]",
    "gpu": "[object GPU]",
    "login": "[object NavigatorLogin]",
    "ink": "[object Ink]",
    "mediaCapabilities": "[object MediaCapabilities]",
    "devicePosture": "[object DevicePosture]",
    "hid": "[object HID]",
    "mediaSession": "[object MediaSession]",
    "permissions": "[object Permissions]",
    "presentation": "[object Presentation]",
    "serial": "[object Serial]",
    "usb": "[object USB]",
    "xr": "[object XRSystem]",
    "storageBuckets": "[object StorageBucketManager]",
    "adAuctionComponents": "function adAuctionComponents() { [native code] }",
    "runAdAuction": "function runAdAuction() { [native code] }",
    "canLoadAdAuctionFencedFrame": "function canLoadAdAuctionFencedFrame() { [native code] }",
    "canShare": "function canShare() { [native code] }",
    "share": "function share() { [native code] }",
    "clearAppBadge": "function clearAppBadge() { [native code] }",
    "getBattery": "function getBattery() { [native code] }",
    "getUserMedia": "function getUserMedia() { [native code] }",
    "requestMIDIAccess": "function requestMIDIAccess() { [native code] }",
    "requestMediaKeySystemAccess": "function requestMediaKeySystemAccess() { [native code] }",
    "setAppBadge": "function setAppBadge() { [native code] }",
    "webkitGetUserMedia": "function webkitGetUserMedia() { [native code] }",
    "clearOriginJoinedAdInterestGroups": "function clearOriginJoinedAdInterestGroups() { [native code] }",
    "createAuctionNonce": "function createAuctionNonce() { [native code] }",
    "joinAdInterestGroup": "function joinAdInterestGroup() { [native code] }",
    "leaveAdInterestGroup": "function leaveAdInterestGroup() { [native code] }",
    "updateAdInterestGroups": "function updateAdInterestGroups() { [native code] }",
    "deprecatedReplaceInURN": "function deprecatedReplaceInURN() { [native code] }",
    "deprecatedURNToURL": "function deprecatedURNToURL() { [native code] }",
    "getInstalledRelatedApps": "function getInstalledRelatedApps() { [native code] }",
    "getInterestGroupAdAuctionData": "function getInterestGroupAdAuctionData() { [native code] }",
    "registerProtocolHandler": "function registerProtocolHandler() { [native code] }",
    "unregisterProtocolHandler": "function unregisterProtocolHandler() { [native code] }",
}

# Object.keys(window) — Chromium capture (order preserved).
CHROME_WINDOW_ENUMERABLE_KEYS: Final[Tuple[str, ...]] = (
    "window",
    "self",
    "document",
    "name",
    "location",
    "customElements",
    "history",
    "navigation",
    "locationbar",
    "menubar",
    "personalbar",
    "scrollbars",
    "statusbar",
    "toolbar",
    "status",
    "closed",
    "frames",
    "length",
    "top",
    "opener",
    "parent",
    "frameElement",
    "navigator",
    "origin",
    "external",
    "screen",
    "innerWidth",
    "innerHeight",
    "scrollX",
    "pageXOffset",
    "scrollY",
    "pageYOffset",
    "visualViewport",
    "screenX",
    "screenY",
    "outerWidth",
    "outerHeight",
    "devicePixelRatio",
    "event",
    "clientInformation",
    "screenLeft",
    "screenTop",
    "styleMedia",
    "onsearch",
    "onappinstalled",
    "onbeforeinstallprompt",
    "onabort",
    "onbeforeinput",
    "onbeforematch",
    "onbeforetoggle",
    "onblur",
    "oncancel",
    "oncanplay",
    "oncanplaythrough",
    "onchange",
    "onclick",
    "onclose",
    "oncommand",
    "oncontentvisibilityautostatechange",
    "oncontextlost",
    "oncontextmenu",
    "oncontextrestored",
    "oncuechange",
    "ondblclick",
    "ondrag",
    "ondragend",
    "ondragenter",
    "ondragleave",
    "ondragover",
    "ondragstart",
    "ondrop",
    "ondurationchange",
    "onemptied",
    "onended",
    "onerror",
    "onfocus",
    "onformdata",
    "oninput",
    "oninvalid",
    "onkeydown",
    "onkeypress",
    "onkeyup",
    "onload",
    "onloadeddata",
    "onloadedmetadata",
    "onloadstart",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onmousewheel",
    "onpause",
    "onplay",
    "onplaying",
    "onprogress",
    "onratechange",
    "onreset",
    "onresize",
    "onscroll",
    "onscrollend",
    "onsecuritypolicyviolation",
    "onseeked",
    "onseeking",
    "onselect",
    "onslotchange",
    "onstalled",
    "onsubmit",
    "onsuspend",
    "ontimeupdate",
    "ontoggle",
    "onvolumechange",
    "onwaiting",
    "onwebkitanimationend",
    "onwebkitanimationiteration",
    "onwebkitanimationstart",
    "onwebkittransitionend",
    "onwheel",
    "onauxclick",
    "ongotpointercapture",
    "onlostpointercapture",
    "onpointerdown",
    "onpointermove",
    "onpointerup",
    "onpointercancel",
    "onpointerover",
    "onpointerout",
    "onpointerenter",
    "onpointerleave",
    "onselectstart",
    "onselectionchange",
    "onanimationcancel",
    "onanimationend",
    "onanimationiteration",
    "onanimationstart",
    "ontransitionrun",
    "ontransitionstart",
    "ontransitionend",
    "ontransitioncancel",
    "onbeforexrselect",
    "onafterprint",
    "onbeforeprint",
    "onbeforeunload",
    "onhashchange",
    "onlanguagechange",
    "onmessage",
    "onmessageerror",
    "onoffline",
    "ononline",
    "onpagehide",
    "onpageshow",
    "onpopstate",
    "onrejectionhandled",
    "onstorage",
    "onunhandledrejection",
    "onunload",
    "isSecureContext",
    "crossOriginIsolated",
    "scheduler",
    "performance",
    "trustedTypes",
    "crypto",
    "indexedDB",
    "localStorage",
    "sessionStorage",
    "alert",
    "atob",
    "blur",
    "btoa",
    "cancelAnimationFrame",
    "cancelIdleCallback",
    "captureEvents",
    "clearInterval",
    "clearTimeout",
    "close",
    "confirm",
    "createImageBitmap",
    "fetch",
    "find",
    "focus",
    "getComputedStyle",
    "getSelection",
    "matchMedia",
    "moveBy",
    "moveTo",
    "open",
    "postMessage",
    "print",
    "prompt",
    "queueMicrotask",
    "releaseEvents",
    "reportError",
    "requestAnimationFrame",
    "requestIdleCallback",
    "resizeBy",
    "resizeTo",
    "scroll",
    "scrollBy",
    "scrollTo",
    "setInterval",
    "setTimeout",
    "stop",
    "structuredClone",
    "webkitCancelAnimationFrame",
    "webkitRequestAnimationFrame",
    "chrome",
    "crashReport",
    "cookieStore",
    "ondevicemotion",
    "ondeviceorientation",
    "ondeviceorientationabsolute",
    "onpointerrawupdate",
    "caches",
    "documentPictureInPicture",
    "sharedStorage",
    "fetchLater",
    "getScreenDetails",
    "queryLocalFonts",
    "showDirectoryPicker",
    "showOpenFilePicker",
    "showSaveFilePicker",
    "originAgentCluster",
    "viewport",
    "onpageswap",
    "onpagereveal",
    "credentialless",
    "fence",
    "launchQueue",
    "speechSynthesis",
    "onscrollsnapchange",
    "onscrollsnapchanging",
    "ongamepadconnected",
    "ongamepaddisconnected",
    "webkitRequestFileSystem",
    "webkitResolveLocalFileSystemURL",
)

# --- Firefox — captured at v148 ---
FIREFOX_DOCUMENT_OWN_KEYS: Final[Tuple[str, ...]] = ("location",)

FIREFOX_IN_WINDOW_BITS: Final[Tuple[int, ...]] = (0, 0, 0, 0, 0, 1, 1)

FIREFOX_NAVIGATOR_PROTOTYPE_KEYS: Final[Tuple[str, ...]] = (
    "javaEnabled",
    "getGamepads",
    "requestMIDIAccess",
    "mozGetUserMedia",
    "sendBeacon",
    "requestMediaKeySystemAccess",
    "getAutoplayPolicy",
    "registerProtocolHandler",
    "taintEnabled",
    "permissions",
    "mimeTypes",
    "plugins",
    "pdfViewerEnabled",
    "doNotTrack",
    "maxTouchPoints",
    "mediaCapabilities",
    "oscpu",
    "vendor",
    "vendorSub",
    "productSub",
    "cookieEnabled",
    "buildID",
    "mediaDevices",
    "serviceWorker",
    "credentials",
    "clipboard",
    "mediaSession",
    "userActivation",
    "wakeLock",
    "login",
    "globalPrivacyControl",
    "webdriver",
    "hardwareConcurrency",
    "gpu",
    "geolocation",
    "appCodeName",
    "appName",
    "appVersion",
    "platform",
    "userAgent",
    "product",
    "language",
    "languages",
    "locks",
    "onLine",
    "storage",
)

FIREFOX_NAVIGATOR_STATIC_STRINGS: Final[Dict[str, str]] = {
    "javaEnabled": "function javaEnabled() {\n    [native code]\n}",
    "getGamepads": "function getGamepads() {\n    [native code]\n}",
    "requestMIDIAccess": "function requestMIDIAccess() {\n    [native code]\n}",
    "mozGetUserMedia": "function mozGetUserMedia() {\n    [native code]\n}",
    "sendBeacon": "function sendBeacon() {\n    [native code]\n}",
    "requestMediaKeySystemAccess": "function requestMediaKeySystemAccess() {\n    [native code]\n}",
    "getAutoplayPolicy": "function getAutoplayPolicy() {\n    [native code]\n}",
    "registerProtocolHandler": "function registerProtocolHandler() {\n    [native code]\n}",
    "taintEnabled": "function taintEnabled() {\n    [native code]\n}",
    "permissions": "[object Permissions]",
    "mimeTypes": "[object MimeTypeArray]",
    "plugins": "[object PluginArray]",
    "pdfViewerEnabled": "true",
    "doNotTrack": "1",
    "maxTouchPoints": "0",
    "mediaCapabilities": "[object MediaCapabilities]",
    "oscpu": "Intel Mac OS X 10.15",
    "vendor": "",
    "vendorSub": "",
    "productSub": "20100101",
    "cookieEnabled": "true",
    "buildID": "20181001000000",
    "mediaDevices": "[object MediaDevices]",
    "serviceWorker": "[object ServiceWorkerContainer]",
    "credentials": "[object CredentialsContainer]",
    "clipboard": "[object Clipboard]",
    "mediaSession": "[object MediaSession]",
    "userActivation": "[object UserActivation]",
    "wakeLock": "[object WakeLock]",
    "login": "[object NavigatorLogin]",
    "globalPrivacyControl": "false",
    "webdriver": "false",
    "hardwareConcurrency": "12",
    "gpu": "[object GPU]",
    "geolocation": "[object Geolocation]",
    "appCodeName": "Mozilla",
    "appName": "Netscape",
    "appVersion": "5.0 (Macintosh)",
    "platform": "MacIntel",
    "product": "Gecko",
    "onLine": "true",
    "locks": "[object LockManager]",
    "storage": "[object StorageManager]",
}

FIREFOX_WINDOW_ENUMERABLE_KEYS: Final[Tuple[str, ...]] = (
    "close",
    "stop",
    "focus",
    "blur",
    "open",
    "alert",
    "confirm",
    "prompt",
    "print",
    "postMessage",
    "captureEvents",
    "releaseEvents",
    "getSelection",
    "getComputedStyle",
    "matchMedia",
    "moveTo",
    "moveBy",
    "resizeTo",
    "resizeBy",
    "scroll",
    "scrollTo",
    "scrollBy",
    "getDefaultComputedStyle",
    "scrollByLines",
    "scrollByPages",
    "updateCommands",
    "find",
    "dump",
    "setResizable",
    "requestIdleCallback",
    "cancelIdleCallback",
    "requestAnimationFrame",
    "cancelAnimationFrame",
    "reportError",
    "btoa",
    "atob",
    "setTimeout",
    "clearTimeout",
    "setInterval",
    "clearInterval",
    "queueMicrotask",
    "createImageBitmap",
    "structuredClone",
    "fetch",
    "self",
    "name",
    "history",
    "navigation",
    "customElements",
    "locationbar",
    "menubar",
    "personalbar",
    "scrollbars",
    "statusbar",
    "toolbar",
    "status",
    "closed",
    "event",
    "frames",
    "length",
    "opener",
    "parent",
    "frameElement",
    "navigator",
    "clientInformation",
    "external",
    "screen",
    "innerWidth",
    "innerHeight",
    "scrollX",
    "pageXOffset",
    "scrollY",
    "pageYOffset",
    "screenLeft",
    "screenTop",
    "screenX",
    "screenY",
    "outerWidth",
    "outerHeight",
    "performance",
    "mozInnerScreenX",
    "mozInnerScreenY",
    "devicePixelRatio",
    "scrollMaxX",
    "scrollMaxY",
    "fullScreen",
    "ondevicemotion",
    "ondeviceorientation",
    "ondeviceorientationabsolute",
    "InstallTrigger",
    "visualViewport",
    "cookieStore",
    "originAgentCluster",
    "crypto",
    "onabort",
    "onblur",
    "onfocus",
    "oncancel",
    "onauxclick",
    "onbeforeinput",
    "onbeforematch",
    "onbeforetoggle",
    "oncanplay",
    "oncanplaythrough",
    "onchange",
    "onclick",
    "onclose",
    "oncontentvisibilityautostatechange",
    "oncontextlost",
    "oncontextmenu",
    "oncommand",
    "oncontextrestored",
    "oncopy",
    "oncuechange",
    "oncut",
    "ondblclick",
    "ondrag",
    "ondragend",
    "ondragenter",
    "ondragexit",
    "ondragleave",
    "ondragover",
    "ondragstart",
    "ondrop",
    "ondurationchange",
    "onemptied",
    "onended",
    "onformdata",
    "oninput",
    "oninvalid",
    "onkeydown",
    "onkeypress",
    "onkeyup",
    "onload",
    "onloadeddata",
    "onloadedmetadata",
    "onloadstart",
    "onmousedown",
    "onmouseenter",
    "onmouseleave",
    "onmousemove",
    "onmouseout",
    "onmouseover",
    "onmouseup",
    "onwheel",
    "onpaste",
    "onpause",
    "onplay",
    "onplaying",
    "onprogress",
    "onratechange",
    "onreset",
    "onresize",
    "onscroll",
    "onscrollend",
    "onsecuritypolicyviolation",
    "onseeked",
    "onseeking",
    "onselect",
    "onslotchange",
    "onstalled",
    "onsubmit",
    "onsuspend",
    "ontimeupdate",
    "onvolumechange",
    "onwaiting",
    "onselectstart",
    "onselectionchange",
    "ontoggle",
    "onpointercancel",
    "onpointerdown",
    "onpointerup",
    "onpointermove",
    "onpointerout",
    "onpointerover",
    "onpointerenter",
    "onpointerleave",
    "onpointerrawupdate",
    "ongotpointercapture",
    "onlostpointercapture",
    "onmozfullscreenchange",
    "onmozfullscreenerror",
    "onanimationcancel",
    "onanimationend",
    "onanimationiteration",
    "onanimationstart",
    "ontransitioncancel",
    "ontransitionend",
    "ontransitionrun",
    "ontransitionstart",
    "onwebkitanimationend",
    "onwebkitanimationiteration",
    "onwebkitanimationstart",
    "onwebkittransitionend",
    "onerror",
    "speechSynthesis",
    "onafterprint",
    "onbeforeprint",
    "onbeforeunload",
    "onhashchange",
    "onlanguagechange",
    "onmessage",
    "onmessageerror",
    "onoffline",
    "ononline",
    "onpagehide",
    "onpageshow",
    "onpopstate",
    "onrejectionhandled",
    "onstorage",
    "onunhandledrejection",
    "onunload",
    "ongamepadconnected",
    "ongamepaddisconnected",
    "localStorage",
    "origin",
    "crossOriginIsolated",
    "isSecureContext",
    "indexedDB",
    "caches",
    "scheduler",
    "trustedTypes",
    "sessionStorage",
    "window",
    "document",
    "location",
    "top",
)


def sdk_r_pick(seq: Tuple[str, ...], rng) -> Optional[str]:
    """SDK R(): random element; empty -> None (JSON null)."""
    if not seq:
        return None
    return rng.choice(seq)


def sdk_t_string(
    rng,
    prototype_keys: Tuple[str, ...],
    static_strings: Dict[str, str],
    *,
    user_agent: str,
    language: str,
    languages_joined: str,
) -> str:
    """SDK T(): random prototype key, U+2212, navigator[k].toString() (approx)."""
    k = rng.choice(prototype_keys)
    if k == "userAgent":
        v = user_agent
    elif k == "language":
        v = language
    elif k == "languages":
        v = languages_joined
    else:
        v = static_strings.get(k)
    if v is None:
        return k
    return f"{k}\u2212{v}"
